// build.js
// Regenerates the in-page FALLBACK data block in index.html from data/*.json.
//
// Why: the site is now a single page (index.html) that fetches
// data/songs.json, data/people.json, data/albums.json, data/posts.json and
// data/categories.json at runtime. The FALLBACK object in index.html's
// <script> is only a safety net for when those fetches fail (e.g. the page
// is opened straight from disk, or the JSON files 404). This script keeps
// that safety net in sync with the real data so it never goes stale.
//
// Run this after editing anything in /data, or wire it into your GitHub
// Action the same way the old build.js was used.

const fs = require('fs');

const read = (p, fallback = []) => {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); }
  catch { return fallback; }
};

const posts = read('data/posts.json');
const people = read('data/people.json');
const songs = read('data/songs.json');
const albums = read('data/albums.json');
const categories = read('data/categories.json');

// Only keep the fields the FALLBACK object actually uses, so the block
// stays small and doesn't leak unrelated data into the fallback path.
const slimSongs = songs.map(s => ({
  id: s.id, title: s.title, artist: s.artist, year: s.year,
  cover: s.cover, coverEmoji: s.coverEmoji, audio: s.audio,
  badges: s.badges, about: s.about
}));

const slimPeople = people.map(p => ({
  id: p.id, name: p.name, handle: p.handle, role: p.role,
  tags: p.tags, avatar: p.avatar, bio: p.bio
}));

const slimPosts = posts.map(p => ({
  id: p.id, title: p.title, date: p.date, category: p.category,
  subcategory: p.subcategory, blocks: p.blocks
}));

const fallback = {
  songs: slimSongs,
  people: slimPeople,
  albums,
  posts: slimPosts,
  categories: []
};

const block = `// FALLBACK_START — regenerated by build.js from data/*.json, do not hand-edit the values below\nconst FALLBACK = ${JSON.stringify(fallback, null, 2)};\n// FALLBACK_END`;

const file = 'index.html';
let src = fs.readFileSync(file, 'utf8');
const re = /\/\/ FALLBACK_START[\s\S]*?\/\/ FALLBACK_END/;

if (!re.test(src)) {
  console.error('Could not find FALLBACK_START/FALLBACK_END markers in index.html — aborting.');
  process.exit(1);
}

src = src.replace(re, block);
fs.writeFileSync(file, src);
console.log(`built: synced ${songs.length} songs, ${people.length} people, ${posts.length} posts into FALLBACK block`);
